spring:
  # H2 DATABASE CONFIG
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    schema: classpath:/db/schema-h2.sql
    data: classpath:/db/data-h2.sql
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
    platform: h2
    initialization-mode: always
    continue-on-error: true
  h2:
    console:
      enabled: true
      path: /console

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.XXXX.vas.main.entity
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: h2
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#webApi web package
web-api-packages: com.XXXX.vas.main.web
#async service package
async-service-impl-packages: com.XXXX.vas.main.service.impl,com.XXXX.vas.main.service2.impl
#http service port
http-server-port: 8989
#worker thread pool
worker-pool-size: 40
#async service instance, suggest equal with cpu core
async-service-instances: 1
